/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_mogujie_algo_openvino_jni_MoguOpenvino_InputBlob */

#ifndef _Included_com_mogujie_algo_openvino_jni_MoguOpenvino_InputBlob
#define _Included_com_mogujie_algo_openvino_jni_MoguOpenvino_InputBlob
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
