/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mogujie_algo_openvino_jni_MoguOpenvino_OutputBlob */

#ifndef _Included_com_mogujie_algo_openvino_jni_MoguOpenvino_OutputBlob
#define _Included_com_mogujie_algo_openvino_jni_MoguOpenvino_OutputBlob
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
